import { model, Schema } from "mongoose";

const orderSchema = new Schema(
  {
    userId: { type: Schema.Types.ObjectId, ref: "user", required: true },
    name: { type: String, required: true },
    hotelId: { type: String },
    hotelFGOId: { type: String },
    bdmId: { type: String },
    orderBy: { type: String },
    cityName: { type: String },
    address: { type: String, required: true },
    country: { type: String },
    state: { type: String },
    postalCode: { type: Number },
    email: { type: String},
    mobNo: { type: Number, required: true },
    gst: { type: String },
    fssai: { type: String },
    pan: { type: String },
    vendorId: { type: String },
    orderItems: { type: Array },
    paymentMethod: { type: String },
    shippingPrice: { type: Number },
    totalPrice: { type: Number },
    rewardPoints: { type: Number },
    rewardPointsUsed: { type: Number },
    iNo: { type: String },
    oNo: { type: String },
    iNoOC: { type: String },
    deliveryAt: { type: Date },
    isPaid: { type: Boolean, default: false },
    orderStatus: { type: String, default: "ordered" },
    deliveredDate: { type: Date },
    cancelledDate: { type: Date },
    tracking_id: { type: String },
    bank_ref_no: { type: String },
    paidAt: { type: Date },
    payment_mode: { type: String },
    deliveredBy: { type: String },
    card_name: { type: String },
    lat: { type: String },
    lng: { type: String },
    mapUrl: { type: String },
    platformOrderedBy: { type: String },
    paymentStatus: { type: String, default: "Payment Pending" },
    isTemp: { type: Boolean, default: false },
    isLocationVerified: { type: Boolean, default: false },
    assignedTo: {
      helper: { type: String },
      helperId: { type: String },
      driver: { type: String },
      driverId: { type: String },
      vehicle: { type: String },
      vehicleId: { type: String },
      isAssigned: { type: Boolean, default: false },
      assignedBy: { name: { type: String }, id: { type: String } },
      assignedAt: { type: Date },
      priority: { type: Number },
      otherHelpers: { type: Array },
    },
    paymentImg: [
      {
        file: { type: String },
      },
    ],
    modified: {
      isModified: { type: Boolean, default: false },
      modifiedBy: { type: String },
    },
    paymentInfo: [
      {
        cashCollected: { type: Number },
        online: { type: Number },
        utr: { type: String },
        utrImage: { type: String },
        date: { type: String },
        reason: { type: String },
        cheaqueImg: { type: String },
        cheaqueAmount: { type: Number },
        cheaqueNo: { type: String },
        pendingAmount: { type: Number },
        onlinePaymentImage: { type: String },
        collectedAt: { type: String },
        collectedBy: { type: String },
        cheaqueStatus: { type: String, default: "InTransit" },
      },
    ],
    comment: { type: String, default: null },
    paymentAudited: { type: Boolean, default: false },
    deliveryData: {
      cashCollected: { type: Number },
      online: { type: Number },
      utr: { type: String },
      reason: { type: String },
      cheaqueImg: { type: String },
      cheaqueAmount: { type: Number },
      cheaqueNo: { type: String },
      pendingAmount: { type: Number },
      onlinePaymentImage: { type: String },
      collectedAt: { type: String },
    },
    deliveredFrom: { type: String, default: "Order Panel" },
    history: [
      {
        status: { type: String },
        createdAt: { type: String },
        userName: { type: String },
      },
    ],
    tempPaymentInfo: [
      {
        cashCollected: { type: Number },
        online: { type: Number },
        utr: { type: String },
        utrImage: { type: String },
        date: { type: String },
        reason: { type: String },
        cheaqueImg: { type: String },
        cheaqueAmount: { type: Number },
        cheaqueNo: { type: String },
        pendingAmount: { type: Number },
        onlinePaymentImage: { type: String },
        collectedAt: { type: String },
        cheaqueStatus: { type: String, default: "InTransit" },
        deliveredBy: { type: Object },
        isCollected: { type: Boolean, default: false },
      },
    ],
    tempReturnedProducts: [
      {
        sku: { type: String },
        quantity: { type: String },
        basePrice: { type: Number },
      },
    ],
    deliveryData: {
      deliveredBy: { type: Object },
      startAt: { type: String },
      deliverySelfie: { type: String },
      deliveryLocation: { lat: { type: String }, lng: { type: String } },
    },
    dpCapturedData: {
      user: { type: Object },
      orderStatus: { type: String },
      updatedAt: { type: String },
      isAudited: { type: Boolean, default: false },
    },
    showInAssignment: { type: Boolean, default: true },
  },
  { timestamps: true }
);

export default model("order", orderSchema);
